//
//  artworks.swift
//  UrbanCanvas
//
//  Created by Apprenant 77 on 02/07/2026.
//

import MapKit

let artworks: [Artwork] = [
    Artwork(name: "Arga",
            description: "Painted during the ARTURb 2025 artistic residency",
            imageName: "arga",
            artType: "Mural",
            condition: "Bon",
            date: "26/09/2025",
            author: artists[1],
            localisation: "Lagos",
            address: "R. Convento Sra. da Glória 25 19, 8600-315 Lagos, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 37.1060065, longitude: -8.6773494)),
    
    Artwork(name: "Distance is not a loss of closeness",
            description: "Une œuvre touchante qui explore la distance et la force des relations humaines malgré l'éloignement.",
            imageName: "distance-is-not",
            artType: "Calligraphie",
            condition: "Moyen",
            date: "17/02/2025",
            author: artists[1],
            localisation: "Cascais",
            address: "R. Estrela do Mar 27, 2750-200 Cascais, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 38.7038104, longitude: -9.4421282)),
    
    Artwork(name: "Half-pipe Jam",
            description: "Half-pipe collaborative painting.",
            imageName: "half-pipe-jam",
            artType: "Stencil",
            condition: "Bon",
            date: "27/12/2024",
            author: artists[1],
            localisation: "Cascais",
            address: "Torre Skatepark, R. Pesqueiros, 2750-762 Cascais, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 38.7020162, longitude: -9.4416486)),
    
    Artwork(name: "Volt",
            description: "Une fresque colorée et dynamique peinte directement sur un grand transformateur électrique extérieur.",
            imageName: "placeholder",
            artType: "Mosaique",
            condition: "Mauvais",
            date: "25/03/2026",
            author: artists[1],
            localisation: "São Domingos de Rana",
            address: "Praça David Mourão Ferreira 601, 2785-720 São Domingos de Rana, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 38.72779, longitude: -9.3284118)),
    
    Artwork(name: "Infinito Mask",
            description: "Artwork created for the Infinito Festival. It represents an anonymous face that literally wears the symbols of its community, carrying a unique identity into the DNA of the neighborhood.",
            imageName: "placeholder",
            artType: "Invaders",
            condition: "Bon",
            date: "20/09/2024",
            author: artists[2],
            localisation: "Cascais",
            address: "R. Caravelas 23, 2750-200 Cascais, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 38.7036328, longitude: -9.4409417)),
    Artwork(name: "ontem, hoje e amanhã",
            description: "The mural painted by Jorge Charrua symbolizes the historical celebration of the 25th of April, while also acts as a reminder that freedom is a constant struggle. This piece is part of The Circuit of Valença, organized by FOmE and the Municipality of Valença.",
            imageName: "placeholder",
            artType: "Mural",
            condition: "Bon",
            date: "31/10/2024",
            author: artists[3],
            localisation: "Valença",
            address: "Av. Sá Carneiro 2, 4930-678 Valença, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 42.0228345, longitude: -8.6414124)),
    
    Artwork(name: "Núria",
            description: "Mural made for @stoneartpt. The painting had as inspiration the process of transforming natural stone into a piece of art, exploring the physical effort and the marks it leaves on the artist's body.",
            imageName: "placeholder",
            artType: "Calligraphie",
            condition: "Moyen",
            date: "30/08/2021",
            author: artists[3],
            localisation: "Alcaria",
            address: "G5RM+F9 Alcaria, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 39.5411654, longitude: -8.8166103)),
    
    Artwork(name: "Cherish Our Bonds",
            description: "Jorge Charrua is one of the artists of MurArcos 2025. His work stands out for the presence of the human figure within a world of urban symbols and iconography, blending memory, empowerment, and references from art history.",
            imageName: "placeholder",
            artType: "Stencil",
            condition: "Bon",
            date: "28/06/2025",
            author: artists[3],
            localisation: "Arcos de Valdevez",
            address: "R. Dr. António José Pimenta Ribeiro 24, 4970-455 Arcos de Valdevez, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 41.8485512, longitude: -8.4222301)),
    
    Artwork(name: "Untitled",
            description: "Fresque réalisée dans le cadre du festival Cubo Magico, explorant les thématiques iconographiques chères à l'artiste.",
            imageName: "placeholder",
            artType: "Mosaique",
            condition: "Mauvais",
            date: "23/06/2023",
            author: artists[3],
            localisation: "Viseu",
            address: "Largo Maj. Monteiro Leite 90, 3500-084 Viseu, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 40.6635006, longitude: -7.9085263)),
    
    Artwork(name: "Karu",
            description: "The idea emerged after a painting I did in 2018 in which the person I portrayed had highly androgynous features. I wanted to further explore the concept about people whose physical traits are not reliable for a society that forces labels on everyone.",
            imageName: "placeholder",
            artType: "Mural",
            condition: "Bon",
            date: "27/10/2019",
            author: artists[3],
            localisation: "Leiria",
            address: "Av. 25 de Abril 11, 2400-137 Leiria, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 39.7475455, longitude: -8.8143028)),
    
    Artwork(name: "Composition Urbaine",
            description: "Une œuvre monumentale typique du collectif, jouant sur les contrastes de couleurs et les formes géométriques complexes.",
            imageName: "placeholder",
            artType: "Invaders",
            condition: "Bon",
            date: "01/01/2020",
            author: artists[4],
            localisation: "Matosinhos",
            address: "R. Goa 8, 4450-231 Matosinhos, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 41.183728, longitude: -8.6809805)),
    
    Artwork(name: "Rupture",
            description: "Intervention sur mobilier urbain transformant un élément fonctionnel de la ville en une pièce de design graphique.",
            imageName: "placeholder",
            artType: "Calligraphie",
            condition: "Moyen",
            date: "01/01/2021",
            author: artists[4],
            localisation: "Viseu",
            address: "Cidade Salamanca 1, 3500 Viseu, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 40.6651485, longitude: -7.9064097)),
    
    Artwork(name: "Porto Collective",
            description: "Collective artwork from Porto artists. Full street exhibition.",
            imageName: "placeholder",
            artType: "Mural",
            condition: "Bon",
            date: "08/12/2025",
            author: artists[4],
            localisation: "Porto",
            address: "R. Cmte. Rodolfo de Araújo, Porto, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 41.1502069, longitude: -8.6011568)),
    
    Artwork(name: "Cheta",
            description: "This work by the artists Draw & Contra honours a typical character from the city of Águeda, Zé Cheta, un exemple d'empathie et de diversité.",
            imageName: "placeholder",
            artType: "Stencil",
            condition: "Bon",
            date: "31/07/2020",
            author: artists[4],
            localisation: "Águeda",
            address: "R. Eng. José Bastos Xavier 33, 3750-115 Águeda, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 40.5774328, longitude: -8.4460564)),
    
    Artwork(name: "Untitled",
            description: "Une fresque abstraite jouant sur les textures et les superpositions, caractéristique de l'évolution du style du collectif.",
            imageName: "placeholder",
            artType: "Mural",
            condition: "Mauvais",
            date: "12/05/2024",
            author: artists[4],
            localisation: "Lisbonne",
            address: "R. Gualdim Pais 144, 1900-284 Lisboa, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 38.7307377, longitude: -9.1165062)),
    Artwork(name: "Game On",
            description: "Une pièce de graffiti dynamique avec un lettrage complexe réalisée dans le cadre du festival GAME ON! Jam 2024.",
            imageName: "placeholder",
            artType: "Mural",
            condition: "Moyen",
            date: "02/03/2024",
            author: artists[5], 
            localisation: "Póvoa de Santa Iria",
            address: "R. Prof. Victor Manuel Morais 17, 2625-219 Póvoa de Santa Iria, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 38.8604267, longitude: -9.0672941)),
    
    Artwork(name: "Untitled",
            description: "Une fresque combinant lettrage sauvage et codes classiques du graffiti urbain sur un mur extérieur de la capitale.",
            imageName: "placeholder",
            artType: "Stencil",
            condition: "Bon",
            date: "30/11/2021",
            author: artists[5],
            localisation: "Lisbonne",
            address: "R. do Rio Coura 1, 1600-708 Lisboa, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 38.7704687, longitude: -9.1882084)),
    Artwork(name: "Humans arent real",
            description: "Wheatpaste based on an original acrylic on paper. A raw reflection on modern human connectivity.",
            imageName: "placeholder",
            artType: "Stencil",
            condition: "Mauvais",
            date: "14/07/2024",
            author: artists[6],
            localisation: "Lisbonne",
            address: "Largo São Domingos 6 8, 1150-114 Lisboa, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 38.7148485, longitude: -9.1388961)),
    
    Artwork(name: "Humans arent real 2",
            description: "A second iteration of the iconic paste-up piece, layered directly onto the streets of Lisbon.",
            imageName: "placeholder",
            artType: "Mural",
            condition: "Bon",
            date: "01/01/2025",
            author: artists[6],
            localisation: "Lisbonne",
            address: "Largo São Domingos 7, 1100-201 Lisboa, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 38.7148556, longitude: -9.138969)),
    
    Artwork(name: "A horse or a girafe",
            description: "An intriguing street art piece playing with abstract animal silhouettes and urban perception.",
            imageName: "placeholder",
            artType: "Mosaique",
            condition: "Moyen",
            date: "01/01/2025",
            author: artists[6],
            localisation: "Lisbonne",
            address: "Praça Dom Pedro IV 60, 1249-970 Lisboa, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 38.7142557, longitude: -9.1397653)),
    
    Artwork(name: "Untitled",
            description: "An expressive paste-up installation interacting with the architecture of the local creative hub.",
            imageName: "placeholder",
            artType: "Calligraphie",
            condition: "Mauvais",
            date: "17/12/2023",
            author: artists[6],
            localisation: "Lisbonne",
            address: "R. Rodrigues de Faria 13, 1300-023 Lisboa, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 38.7043189, longitude: -9.1771778)),
    
    Artwork(name: "Insane World",
            description: "A satirical acrylic paper paste-up depicting the chaotic and beautiful complexities of our world.",
            imageName: "placeholder",
            artType: "Invaders",
            condition: "Moyen",
            date: "17/12/2023",
            author: artists[6],
            localisation: "Lisbonne",
            address: "Av. da Índia 6, 1300-299 Lisboa, Portugal",
            coordinates: CLLocationCoordinate2D(latitude: 38.7026821, longitude: -9.1753323))
    
]

func artworkArrayFilter(artList :[Artwork], artStyle :String) -> [Artwork] {
    var filteredArray :[Artwork] = []
    if artStyle == "Tous" {
        return artList
    }
    for art in artList {
        if art.artType == artStyle {
            filteredArray.append(art)
        }
    }
    return filteredArray
}
